### ISSUE TITLE
Update to OpenMM 7.2 code?

### ISSUE THREAD

**Issue by jchodera** [FoldingAtHome/openmm#23]
@peastman : While OpenMM 7.2 has just been released, the non-forcefield code has been super stable for quite some time. What do you think about updating the core code to match 7.2 and pushing ahead with a modern core 22? @gbowman can help coordinate, and hopefully @jcoffland should be able to lead in putting this together.

**Comment by peastman** [comment]
Sounds good.

**Comment by jchodera** [comment]
Tagging @gbowman and @peastman: It would be great to get this updated and see if we can have @jcoffland take a stab at building core22 from the 7.2.1-based OpenMM release.

**Comment by peastman** [comment]
What are you waiting on me for?

**Comment by jchodera** [comment]
Was there anything special needed to update this fork? I can't recall why we needed a separate fork in the first place and was hoping you recalled what needed to be done. I am happy to take a stab at it!

**Comment by peastman** [comment]
I think it was just so we could have a stable version for building the core against, and could add individual fixes to it without needing to pull in all changes from the main repository.  Since we're now starting a new core, let's begin over from the 7.2.1 code.

**Comment by jchodera** [comment]
I've just updated this to track the `7.2_branch` from http://github.com/pandegroup/openmm

**Comment by peastman** [comment]
If core22 is going to be based on OpenMM 7.2.2, we should also merge in https://github.com/pandegroup/openmm/pull/2102.  That's the fix for the CUDA error that occasionally showed up in large systems.

**Comment by jchodera** [comment]
Will there be a 7.2.3, or should we just pull in that change?

**Comment by peastman** [comment]
No idea whether we'll do a 7.2.3.  For now, go ahead and pull that change in.
