### ISSUE TITLE
Is SHAKE being misused by Core_22 projects?

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/openmm#24]
FAHCore_22 is being developed using a recent version of OpenMM.  It is encountering a significant number of "bad state" failures.

In a discussion of that new FAHCore, an unrelated (?) fact was mentioned that simulations can be accelerated by using larger time-steps provided the mass of the H atoms is redistributed, which let me to this paper: *Long-Time-Step Molecular Dynamics through Hydrogen Mass
Repartitioning* by Chad  W.  Hopkins et.al. out of the University of Florida,

I do not have first hand-knowledge if that paper is being applied to the projects that are failing.   (Somebody should check).  Neither do I know if the routine SHAKE is being use (either tha Windows version of the Linux version for GPUs).

Near the end of that paper, there is a warning that SHAKE will fail with time-steps greater that 1 fs.  Could that be what's causing our Bad State errors?

If so, can a simple test of the timestep be incorporated into calls to SHAKE warning that there may be an upcoming failure?

Obviously I may be complete wrong about all of this.

**Comment by rafwiewiora** [comment]
I'm trying THE FIRST PROJECT USING HMR in internal right now. Obviously we're still working on getting the core stable first on 2 fs. Like I said on Slack - why we're suddenly talking about an old algorithm having anything to do with failures of a new core - I don't understand.

**Comment by bb30994** [comment]
Did you read the segment of that paper explaining what they learned about SHAKE?  There's even a diagram of how the atoms are move back into alignment along the bond and how it can fail.  Do you want me to quote the paper for you?

**Comment by rafwiewiora** [comment]
Explain to me why it's worthwhile pursuing some still unidentified route of debugging on an algorithm that's been successfully used everywhere, to make a more stable core of simply a new version of OpenMM which had no changes to that algorithm but did to many other things.

If you're any more curious about it, please look in the code in this repo and suggest where problems might be, I'm out for now to try to really make the core stable.

**Comment by bb30994** [comment]
Because the authors of that paper reported that they could not run at 2 fs, researched the problem and documented the shorcoming very clearly.  It sure looks like  you're encountering the same problem and you ought to check out the information they provided.

SHAKE has been used "everywhere" but it runs safely at 1 fs but not at 2 fs.

**Comment by peastman** [comment]
This is not related.  Given the particular set of constraints we use, 2 fs is a standard step size to use.  It works fine.
