### ISSUE TITLE
What happened to windowsExportCuda.h?

### ISSUE THREAD

**Issue by NobodyFAH** [FoldingAtHome/openmm#39]
Hello there,

I just wanted to ask what happened to the file windowsExportCuda.h from version 7.4.2

Is it no longer needed, has it been moved or something similar?
Thanks for your answers

**Comment by NobodyFAH** [comment]
I would ask on the original openmm repo, but I have no rights to open an issue there. I'm asking here instead for that reason, but also because some/most people are in both groups and may be able to help me.

Thank you

**Comment by peastman** [comment]
It's been replaced by windowsExportCommon.h.  Use that instead.

The main OpenMM repo is public.  Anyone can open issues there!

**Comment by NobodyFAH** [comment]
Huh, weird. I'll try again I guess.

Thank you
