### ISSUE TITLE
Backport NaN checks for OpenCL platform

### ISSUE THREAD

**Issue by jchodera** [FoldingAtHome/openmm#4]
We will want to backport the changes from https://github.com/pandegroup/openmm/pull/1178 to address https://github.com/FoldingAtHome/openmm-core/issues/79

**Comment by jchodera** [comment]
Just a reminder that we need to backport these changes.  This issue is apparently causing the donors a lot of problems, and it would be great to get it fixed in a 0.0.13 release.

**Comment by jchodera** [comment]
@peastman: Can we get this backported?

**Comment by jchodera** [comment]
Actually, this is small enough that I can create a PR.  Sorry---I hadn't realized it was such a small patch.

**Comment by peastman** [comment]
Sorry, I'm still catching up on things from while I was on vacation.  But yes, go ahead and create a PR.  It was a very small change.
