### ISSUE TITLE
Cut release for core21-0.0.13

### ISSUE THREAD

**Issue by jchodera** [FoldingAtHome/openmm#7]
We apparently neglected to cut a release for the version of `core21` compiled for 0.0.12.

This is just a reminder that we should cut a release for 0.0.13.

**Comment by jchodera** [comment]
Shoot.  We didn't do this.  Is is too late to create a `core21-0.0.14` tag for the commit prior to your #9, @peastman?

**Comment by peastman** [comment]
You can specify a commit in `git tag`.  It doesn't need to be the latest revision.
